import styles from 'src/styles/Global.module.css'
import Head from "next/head";
import Link from "next/link";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Your Next Shopify App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Your <a href="https://nextjs.org">Next</a> big thing starts here!
                </h1>
                <p className={styles.description}>
                    Build your next non-embedded Shopify app easily.
                    <br/>
                    Most of the necessary setup is ready, so you can get going fast!
                </p>
                <Link href={'/login'}>
                    <button
                        className={styles.button}
                        style={{maxWidth: "fit-content", padding: "1rem", fontSize: "1.6rem"}}
                    >
                        Install App / Login
                    </button>
                </Link>
            </main>
        </div>
    )
}